#! /bin/bash

set -e

psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${AIRFLOW_USER} WITH PASSWORD '${AIRFLOW_PASSWORD}';
    CREATE DATABASE ${AIRFLOW_DB} OWNER ${AIRFLOW_USER};
EOSQL
