services:
  db:
    container_name: postgres_container
    image: postgres:16-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d:ro
    networks:
      - wdp_network

  airflow:
    container_name: airflow_container
    build: .
    ports:
      - ${AIRFLOW_PORT}:8080
    env_file: .env
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_USER}:${AIRFLOW_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${AIRFLOW_DB}
      PYTHONPATH: /opt/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
    command: >
      bash -c "airflow db migrate && airflow standalone"
    networks:
      - wdp_network

  dbt:
    container_name: dbt_container
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    env_file: .env
    volumes:
      - ./dbt/weather_data_pipeline:/usr/app
      - ./dbt:/root/.dbt
    working_dir: /usr/app
    environment:
      DBT_PROFILES_DIR: /root/.dbt
    depends_on:
      - db
    networks:
      - wdp_network
    command: run

volumes:
  pgdata:

networks:
  wdp_network:
    driver: bridge
