name: Python Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Check format
        run: uvx ruff format --check .

      - name: Check lint
        run: uvx ruff check .
